-- Database export via SQLPro (https://www.sqlprostudio.com/allapps.html)
-- Exported by tuannnh at 02-02-2020 10:10.
-- WARNING: This file may contain descructive statements such as DROPs.
-- Please ensure that you are running the script at the proper location.


-- BEGIN TABLE dbo.tbl_article
IF OBJECT_ID('dbo.tbl_article', 'U') IS NOT NULL
DROP TABLE dbo.tbl_article;
GO

CREATE TABLE dbo.tbl_article (
	id int NOT NULL IDENTITY(1,1),
	title varchar(255) NOT NULL,
	shortDescription varchar(255) NOT NULL,
	dateCreate datetime NOT NULL,
	status varchar(10) NOT NULL DEFAULT ('New'),
	content text(16) NOT NULL,
	email varchar(50) NOT NULL
);
GO

ALTER TABLE dbo.tbl_article ADD CONSTRAINT PK__tbl_arti__3213E83F21667B3B PRIMARY KEY (id);
GO

-- Inserting 120 rows into dbo.tbl_article
-- Insert batch #1
INSERT INTO dbo.tbl_article (id, title, shortDescription, dateCreate, status, content, email) VALUES
(22, 'Henan Normal University', 'generate robust partnerships', '2019-01-11 09:06:18', 'Deleted', 'Aliquam sit amet diam in magna bibendum imperdiet.', 'hungtuan.user@gmail.com'),
(23, 'Pennsylvania State University - Abington', 'enable distributed solutions', '2018-02-09 03:05:53', 'Deleted', 'In sagittis dui vel nisl. Duis ac nibh.', 'admin@localhost.com'),
(24, 'Ibra College of Technology', 'extend revolutionary e-tailers', '2019-02-13 08:43:41', 'Deleted', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'admin@localhost.com'),
(25, 'Universidad de Iberoamérica', 'morph innovative e-business', '2018-02-05 18:11:01', 'Active', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'hungtuan.user@gmail.com'),
(26, 'Yasuj University', 'deploy holistic ROI', '2019-01-15 05:59:38', 'New', 'Aenean auctor gravida sem.', 'admin@localhost.com'),
(27, 'Tajik National University', 'enable frictionless eyeballs', '2018-03-30 18:12:07', 'Deleted', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'admin@localhost.com'),
(28, 'Foundation University', 'reintermediate plug-and-play methodologies', '2018-06-07 21:31:55', 'New', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'admin@localhost.com'),
(29, 'Shiraz Payamnoor University', 'extend distributed methodologies', '2018-10-19 03:18:19', 'Deleted', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'hungtuan.user@gmail.com'),
(30, 'Tobb Economics and Technology University', 'matrix turn-key partnerships', '2018-06-29 17:17:23', 'Active', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'admin@localhost.com'),
(31, 'Gansu University of Technology', 'reintermediate viral models', '2019-06-07 05:42:36', 'Active', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 'hungtuan.user@gmail.com'),
(32, 'Belmont Abbey College', 'strategize integrated users', '2019-03-02 18:30:13', 'New', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'hungtuan.user@gmail.com'),
(33, 'Police Academy of Latvia', 'mesh transparent channels', '2019-08-15 16:12:14', 'Active', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'hungtuan.user@gmail.com'),
(34, 'Ecole Supérieure de Commerce de Brest', 'revolutionize leading-edge convergence', '2018-04-20 09:03:26', 'Deleted', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'admin@localhost.com'),
(35, 'University of Batangas', 'streamline innovative deliverables', '2018-09-16 12:53:19', 'Active', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'hungtuan.user@gmail.com'),
(36, 'Osaka University of Economics & Law', 'transition frictionless synergies', '2018-10-26 21:29:01', 'Deleted', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'admin@localhost.com'),
(37, 'Universidad de Granma', 'whiteboard proactive portals', '2019-02-15 20:51:51', 'Deleted', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'hungtuan.user@gmail.com'),
(38, 'Shaqra University', 'grow ubiquitous methodologies', '2019-10-06 05:43:19', 'New', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'hungtuan.user@gmail.com'),
(39, 'Kazakh British Technical University', 'unleash out-of-the-box portals', '2019-08-20 04:14:48', 'Active', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'hungtuan.user@gmail.com'),
(40, 'Institute of Accountancy Arusha', 'benchmark efficient content', '2018-02-28 03:23:08', 'Active', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'admin@localhost.com'),
(41, 'Kilis 7 Aralik University', 'exploit viral applications', '2018-05-14 11:39:11', 'New', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'admin@localhost.com'),
(42, 'South Bank University', 'synthesize rich markets', '2018-10-02 23:11:47', 'New', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'admin@localhost.com'),
(43, 'Tehran University of Medical Sciences', 'incubate viral e-business', '2018-04-06 05:18:23', 'New', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'hungtuan.user@gmail.com'),
(44, 'Ecole des Hautes Etudes Commerciales', 'engineer bricks-and-clicks channels', '2018-08-05 22:58:02', 'Active', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'admin@localhost.com'),
(45, 'University of Applied Sciences Solothurn Northwestern Switzerland', 'embrace impactful ROI', '2018-09-29 20:51:01', 'Active', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'admin@localhost.com'),
(46, 'National University', 'mesh B2C e-tailers', '2019-05-21 21:56:17', 'New', 'Suspendisse potenti.', 'hungtuan.user@gmail.com'),
(47, 'Katowice School of Economics', 'e-enable killer bandwidth', '2019-07-28 12:09:18', 'New', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'admin@localhost.com'),
(48, 'Institut Commercial de Nancy', 'reinvent best-of-breed methodologies', '2018-07-03 04:59:42', 'Active', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'admin@localhost.com'),
(49, 'Qom University of Technology', 'exploit compelling metrics', '2019-07-16 07:17:23', 'New', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'admin@localhost.com'),
(50, 'Osaka Gakuin University', 'exploit leading-edge channels', '2020-01-31 21:26:16', 'Active', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'admin@localhost.com'),
(51, 'University of Perugia', 'cultivate end-to-end e-commerce', '2019-05-27 13:14:18', 'New', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'admin@localhost.com'),
(52, 'Ufa State Petroleum Technological University', 'engineer sticky initiatives', '2019-05-17 06:08:09', 'Active', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'admin@localhost.com'),
(53, 'L.N. Gumilyov Eurasian National University', 'implement bricks-and-clicks portals', '2018-07-27 07:14:29', 'New', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'hungtuan.user@gmail.com'),
(54, 'L.N. Gumilyov Eurasian National University', 'cultivate viral methodologies', '2019-09-28 22:50:08', 'Deleted', 'Vivamus vel nulla eget eros elementum pellentesque.', 'hungtuan.user@gmail.com'),
(55, 'African Virtual University', 'cultivate cross-media niches', '2020-01-03 03:08:56', 'Deleted', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'admin@localhost.com'),
(56, 'Instituto Tecnológico de Morelia', 'synergize 24/365 models', '2018-11-16 20:56:27', 'Active', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'hungtuan.user@gmail.com'),
(57, 'Singapore Institute of Management (SIM)', 'orchestrate leading-edge convergence', '2018-02-20 02:05:44', 'New', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'admin@localhost.com'),
(58, 'Business and Hotel Management School', 'benchmark collaborative systems', '2019-07-02 17:49:26', 'Active', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'admin@localhost.com'),
(59, 'Al-Zaiem Al-Azhari University', 'e-enable cross-media systems', '2019-10-27 14:20:14', 'New', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'admin@localhost.com'),
(60, 'Thunderbird School of Global Management', 'disintermediate e-business supply-chains', '2018-11-04 18:36:53', 'Active', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'admin@localhost.com'),
(61, 'Aligarh Muslim University', 'e-enable virtual partnerships', '2019-07-26 07:18:52', 'New', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'admin@localhost.com'),
(62, 'Humboldt Universität Berlin', 'implement cross-platform users', '2018-05-17 14:37:34', 'New', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'admin@localhost.com'),
(63, 'Free University (Virginia Theological University)', 'incubate open-source networks', '2019-04-06 13:44:09', 'Deleted', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'admin@localhost.com'),
(64, 'Kabul University', 'integrate innovative e-commerce', '2019-08-19 01:47:30', 'Active', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'hungtuan.user@gmail.com'),
(65, 'University of Health Sciences Antigua', 'transform compelling users', '2018-10-06 22:23:23', 'Active', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'hungtuan.user@gmail.com'),
(66, 'Trinity College of Florida', 'optimize customized applications', '2018-05-13 15:32:24', 'New', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'admin@localhost.com'),
(67, 'Jami Institute of Technology', 'enhance sexy infomediaries', '2019-07-19 16:23:33', 'New', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'admin@localhost.com'),
(68, 'Murni Nursing College', 'leverage integrated e-tailers', '2018-11-21 20:44:50', 'New', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'hungtuan.user@gmail.com'),
(69, 'Wentworth Institute of Technology', 'empower best-of-breed users', '2018-09-20 03:00:47', 'Active', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'hungtuan.user@gmail.com'),
(70, 'Suan Dusit Rajabhat University', 'incentivize holistic methodologies', '2018-09-25 18:07:42', 'Deleted', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'admin@localhost.com'),
(71, 'Chiba Institute of Technology', 'strategize dynamic niches', '2018-03-27 10:32:57', 'New', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'admin@localhost.com'),
(72, 'Indian Veterinary Research Institute', 'utilize efficient web-readiness', '2018-12-08 19:35:22', 'Active', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'admin@localhost.com'),
(73, 'Arabian Gulf University', 'implement customized web-readiness', '2018-09-02 20:42:05', 'Active', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'admin@localhost.com'),
(74, 'Mills College', 'innovate sticky eyeballs', '2019-01-12 14:15:43', 'New', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'hungtuan.user@gmail.com'),
(75, 'University of Dammam', 'expedite integrated networks', '2018-02-21 16:32:28', 'Deleted', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'hungtuan.user@gmail.com'),
(76, 'Indiana Wesleyan University', 'enhance end-to-end metrics', '2018-12-27 02:38:59', 'New', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'admin@localhost.com'),
(77, 'West Virginia State College', 'brand transparent platforms', '2018-05-13 19:15:52', 'Active', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'hungtuan.user@gmail.com'),
(78, 'Gujarat University Ahmedabad', 'embrace scalable niches', '2019-01-12 15:45:54', 'New', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'hungtuan.user@gmail.com'),
(79, 'Universidad de Ciencias Empresariales y Sociales', 'mesh plug-and-play communities', '2018-07-12 18:02:53', 'New', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'admin@localhost.com'),
(80, 'Universidad Pedagogica Nacional', 'repurpose mission-critical solutions', '2020-01-28 15:13:49', 'Deleted', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'admin@localhost.com'),
(81, 'COMSATS Institute of Information Technology, Abbottabad', 'morph compelling web services', '2018-07-01 03:33:06', 'Deleted', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'admin@localhost.com'),
(82, 'Henan Normal University', 'generate robust partnerships', '2019-01-11 09:06:18', 'Deleted', 'Aliquam sit amet diam in magna bibendum imperdiet.', 'hungtuan.user@gmail.com'),
(83, 'Pennsylvania State University - Abington', 'enable distributed solutions', '2018-02-09 03:05:53', 'Deleted', 'In sagittis dui vel nisl. Duis ac nibh.', 'admin@localhost.com'),
(84, 'Ibra College of Technology', 'extend revolutionary e-tailers', '2019-02-13 08:43:41', 'Deleted', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'admin@localhost.com'),
(85, 'Universidad de Iberoamérica', 'morph innovative e-business', '2018-02-05 18:11:01', 'Active', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'hungtuan.user@gmail.com'),
(86, 'Yasuj University', 'deploy holistic ROI', '2019-01-15 05:59:38', 'New', 'Aenean auctor gravida sem.', 'admin@localhost.com'),
(87, 'Tajik National University', 'enable frictionless eyeballs', '2018-03-30 18:12:07', 'Deleted', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'admin@localhost.com'),
(88, 'Foundation University', 'reintermediate plug-and-play methodologies', '2018-06-07 21:31:55', 'New', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'admin@localhost.com'),
(89, 'Shiraz Payamnoor University', 'extend distributed methodologies', '2018-10-19 03:18:19', 'Deleted', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'hungtuan.user@gmail.com'),
(90, 'Tobb Economics and Technology University', 'matrix turn-key partnerships', '2018-06-29 17:17:23', 'Active', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'admin@localhost.com'),
(91, 'Gansu University of Technology', 'reintermediate viral models', '2019-06-07 05:42:36', 'Active', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 'hungtuan.user@gmail.com'),
(92, 'Belmont Abbey College', 'strategize integrated users', '2019-03-02 18:30:13', 'New', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'hungtuan.user@gmail.com'),
(93, 'Police Academy of Latvia', 'mesh transparent channels', '2019-08-15 16:12:14', 'Active', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'hungtuan.user@gmail.com'),
(94, 'Ecole Supérieure de Commerce de Brest', 'revolutionize leading-edge convergence', '2018-04-20 09:03:26', 'Deleted', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'admin@localhost.com'),
(95, 'University of Batangas', 'streamline innovative deliverables', '2018-09-16 12:53:19', 'Active', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'hungtuan.user@gmail.com'),
(96, 'Osaka University of Economics & Law', 'transition frictionless synergies', '2018-10-26 21:29:01', 'Deleted', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'admin@localhost.com'),
(97, 'Universidad de Granma', 'whiteboard proactive portals', '2019-02-15 20:51:51', 'Deleted', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'hungtuan.user@gmail.com'),
(98, 'Shaqra University', 'grow ubiquitous methodologies', '2019-10-06 05:43:19', 'New', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'hungtuan.user@gmail.com'),
(99, 'Kazakh British Technical University', 'unleash out-of-the-box portals', '2019-08-20 04:14:48', 'Active', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'hungtuan.user@gmail.com'),
(100, 'Institute of Accountancy Arusha', 'benchmark efficient content', '2018-02-28 03:23:08', 'Active', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'admin@localhost.com'),
(101, 'Kilis 7 Aralik University', 'exploit viral applications', '2018-05-14 11:39:11', 'New', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'admin@localhost.com'),
(102, 'South Bank University', 'synthesize rich markets', '2018-10-02 23:11:47', 'New', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'admin@localhost.com'),
(103, 'Tehran University of Medical Sciences', 'incubate viral e-business', '2018-04-06 05:18:23', 'New', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'hungtuan.user@gmail.com'),
(104, 'Ecole des Hautes Etudes Commerciales', 'engineer bricks-and-clicks channels', '2018-08-05 22:58:02', 'Active', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'admin@localhost.com'),
(105, 'University of Applied Sciences Solothurn Northwestern Switzerland', 'embrace impactful ROI', '2018-09-29 20:51:01', 'Active', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'admin@localhost.com'),
(106, 'National University', 'mesh B2C e-tailers', '2019-05-21 21:56:17', 'New', 'Suspendisse potenti.', 'hungtuan.user@gmail.com'),
(107, 'Katowice School of Economics', 'e-enable killer bandwidth', '2019-07-28 12:09:18', 'New', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'admin@localhost.com'),
(108, 'Institut Commercial de Nancy', 'reinvent best-of-breed methodologies', '2018-07-03 04:59:42', 'Active', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'admin@localhost.com'),
(109, 'Qom University of Technology', 'exploit compelling metrics', '2019-07-16 07:17:23', 'New', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'admin@localhost.com'),
(110, 'Osaka Gakuin University', 'exploit leading-edge channels', '2020-01-31 21:26:16', 'Active', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'admin@localhost.com'),
(111, 'University of Perugia', 'cultivate end-to-end e-commerce', '2019-05-27 13:14:18', 'New', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'admin@localhost.com'),
(112, 'Ufa State Petroleum Technological University', 'engineer sticky initiatives', '2019-05-17 06:08:09', 'Active', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'admin@localhost.com'),
(113, 'L.N. Gumilyov Eurasian National University', 'implement bricks-and-clicks portals', '2018-07-27 07:14:29', 'New', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'hungtuan.user@gmail.com'),
(114, 'L.N. Gumilyov Eurasian National University', 'cultivate viral methodologies', '2019-09-28 22:50:08', 'Deleted', 'Vivamus vel nulla eget eros elementum pellentesque.', 'hungtuan.user@gmail.com'),
(115, 'African Virtual University', 'cultivate cross-media niches', '2020-01-03 03:08:56', 'Deleted', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'admin@localhost.com'),
(116, 'Instituto Tecnológico de Morelia', 'synergize 24/365 models', '2018-11-16 20:56:27', 'Active', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'hungtuan.user@gmail.com'),
(117, 'Singapore Institute of Management (SIM)', 'orchestrate leading-edge convergence', '2018-02-20 02:05:44', 'New', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'admin@localhost.com'),
(118, 'Business and Hotel Management School', 'benchmark collaborative systems', '2019-07-02 17:49:26', 'Active', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'admin@localhost.com'),
(119, 'Al-Zaiem Al-Azhari University', 'e-enable cross-media systems', '2019-10-27 14:20:14', 'New', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'admin@localhost.com'),
(120, 'Thunderbird School of Global Management', 'disintermediate e-business supply-chains', '2018-11-04 18:36:53', 'Active', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'admin@localhost.com'),
(121, 'Aligarh Muslim University', 'e-enable virtual partnerships', '2019-07-26 07:18:52', 'New', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'admin@localhost.com'),
(122, 'Humboldt Universität Berlin', 'implement cross-platform users', '2018-05-17 14:37:34', 'New', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'admin@localhost.com'),
(123, 'Free University (Virginia Theological University)', 'incubate open-source networks', '2019-04-06 13:44:09', 'Deleted', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'admin@localhost.com'),
(124, 'Kabul University', 'integrate innovative e-commerce', '2019-08-19 01:47:30', 'Active', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'hungtuan.user@gmail.com'),
(125, 'University of Health Sciences Antigua', 'transform compelling users', '2018-10-06 22:23:23', 'Active', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'hungtuan.user@gmail.com'),
(126, 'Trinity College of Florida', 'optimize customized applications', '2018-05-13 15:32:24', 'Active', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'admin@localhost.com'),
(127, 'Jami Institute of Technology', 'enhance sexy infomediaries', '2019-07-19 16:23:33', 'New', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'admin@localhost.com'),
(128, 'Murni Nursing College', 'leverage integrated e-tailers', '2018-11-21 20:44:50', 'New', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'hungtuan.user@gmail.com'),
(129, 'Wentworth Institute of Technology', 'empower best-of-breed users', '2018-09-20 03:00:47', 'Active', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'hungtuan.user@gmail.com'),
(130, 'Suan Dusit Rajabhat University', 'incentivize holistic methodologies', '2018-09-25 18:07:42', 'Deleted', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'admin@localhost.com'),
(131, 'Chiba Institute of Technology', 'strategize dynamic niches', '2018-03-27 10:32:57', 'New', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'admin@localhost.com'),
(132, 'Indian Veterinary Research Institute', 'utilize efficient web-readiness', '2018-12-08 19:35:22', 'Active', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'admin@localhost.com'),
(133, 'Arabian Gulf University', 'implement customized web-readiness', '2018-09-02 20:42:05', 'Active', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'admin@localhost.com'),
(134, 'Mills College', 'innovate sticky eyeballs', '2019-01-12 14:15:43', 'New', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'hungtuan.user@gmail.com'),
(135, 'University of Dammam', 'expedite integrated networks', '2018-02-21 16:32:28', 'Deleted', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'hungtuan.user@gmail.com'),
(136, 'Indiana Wesleyan University', 'enhance end-to-end metrics', '2018-12-27 02:38:59', 'New', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'admin@localhost.com'),
(137, 'West Virginia State College', 'brand transparent platforms', '2018-05-13 19:15:52', 'Active', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'hungtuan.user@gmail.com'),
(138, 'Gujarat University Ahmedabad', 'embrace scalable niches', '2019-01-12 15:45:54', 'New', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'hungtuan.user@gmail.com'),
(139, 'Universidad de Ciencias Empresariales y Sociales', 'mesh plug-and-play communities', '2018-07-12 18:02:53', 'New', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'admin@localhost.com'),
(140, 'Universidad Pedagogica Nacional', 'repurpose mission-critical solutions', '2020-01-28 15:13:49', 'Deleted', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'admin@localhost.com'),
(141, 'COMSATS Institute of Information Technology, Abbottabad', 'morph compelling web services', '2018-07-01 03:33:06', 'Deleted', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'admin@localhost.com');

-- END TABLE dbo.tbl_article

-- BEGIN TABLE dbo.tbl_comment
IF OBJECT_ID('dbo.tbl_comment', 'U') IS NOT NULL
DROP TABLE dbo.tbl_comment;
GO

CREATE TABLE dbo.tbl_comment (
	id int NOT NULL IDENTITY(1,1),
	content text(16) NOT NULL,
	commentDate datetime NOT NULL,
	articleId int NOT NULL,
	email varchar(50) NOT NULL
);
GO

ALTER TABLE dbo.tbl_comment ADD CONSTRAINT PK__tbl_comm__3213E83F98514754 PRIMARY KEY (id);
GO

-- Inserting 1 row into dbo.tbl_comment
-- Insert batch #1
INSERT INTO dbo.tbl_comment (id, content, commentDate, articleId, email) VALUES
(45, 'hello', '2020-02-02 10:02:24', 50, 'mail@hungtuan.me');

-- END TABLE dbo.tbl_comment

-- BEGIN TABLE dbo.tbl_user
IF OBJECT_ID('dbo.tbl_user', 'U') IS NOT NULL
DROP TABLE dbo.tbl_user;
GO

CREATE TABLE dbo.tbl_user (
	email varchar(50) NOT NULL,
	name varchar(50) NOT NULL,
	password varchar(64) NOT NULL,
	role varchar(10) NOT NULL DEFAULT ('User'),
	status varchar(10) NOT NULL DEFAULT ('New'),
	token varchar(36) NOT NULL
);
GO

ALTER TABLE dbo.tbl_user ADD CONSTRAINT PK_USER PRIMARY KEY (email);
GO

-- Inserting 3 rows into dbo.tbl_user
-- Insert batch #1
INSERT INTO dbo.tbl_user (email, name, password, role, status, token) VALUES
('admin@localhost.com', 'Administrator', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Admin', 'Active', '123'),
('hungtuan.user@gmail.com', 'Tuan', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'User', 'Active', 'a2c7a1b00c864c2f9c78782d07d9224e'),
('mail@hungtuan.me', 'Hung Tuan', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'User', 'Active', '55538d921de7406796c11d2ce36cd61f');

-- END TABLE dbo.tbl_user

IF OBJECT_ID('dbo.tbl_article', 'U') IS NOT NULL AND OBJECT_ID('dbo.tbl_user', 'U') IS NOT NULL
	ALTER TABLE dbo.tbl_article
	ADD CONSTRAINT Article_fk0
	FOREIGN KEY (email)
	REFERENCES dbo.tbl_user (email)
	ON UPDATE Cascade;

IF OBJECT_ID('dbo.tbl_comment', 'U') IS NOT NULL AND OBJECT_ID('dbo.tbl_article', 'U') IS NOT NULL
	ALTER TABLE dbo.tbl_comment
	ADD CONSTRAINT FK_46
	FOREIGN KEY (articleId)
	REFERENCES dbo.tbl_article (id);

IF OBJECT_ID('dbo.tbl_comment', 'U') IS NOT NULL AND OBJECT_ID('dbo.tbl_user', 'U') IS NOT NULL
	ALTER TABLE dbo.tbl_comment
	ADD CONSTRAINT FK_49
	FOREIGN KEY (email)
	REFERENCES dbo.tbl_user (email);

